/** @fumoca/storage: storage provider interface and built-in providers. See SPECS.md §8. */

export {
  type Alternative,
  alternativeLabel,
  type CellDimension,
  type CellInput,
  type CellRef,
  type Combination,
  cellInDimension,
  combinationCount,
  combinations,
  createCellDimension,
  createGroupDimension,
  createScenario,
  createSensitivity,
  DEFAULT_SCENARIO_SAMPLES,
  DEFAULT_SENSITIVITY_STEP,
  type Dimension,
  dimensionSize,
  type GroupDimension,
  type Override,
  type Scenario,
  type ScenarioBase,
  type SensitivityAnalysis,
  sensitivityIndex,
  type Variant,
  type WhatIfScenario,
} from "./scenario";
export {
  hasNoPeriods,
  lastUsedRow,
  type SeriesIssues,
  seriesIssues,
  sortSeriesSheet,
  suggestPeriod,
} from "./series";
export {
  addSeriesColumn,
  addSheet,
  cellName,
  cellNameError,
  columnNameError,
  createSeriesSheet,
  createSheet,
  createWorkbook,
  FILE_EXTENSION,
  FILE_FORMAT,
  FILE_VERSION,
  findName,
  namedCells,
  nextScenarioName,
  nextSheetName,
  PERIOD_COLUMN,
  parseWorkbook,
  putScenario,
  removeCellName,
  removeScenario,
  renameSeriesColumn,
  SERIES_TYPES,
  type SeriesSettings,
  type SeriesType,
  type Sheet,
  serializeWorkbook,
  setCell,
  setCellName,
  setSeriesSettings,
  type Workbook,
  WorkbookFormatError,
} from "./workbook";
