/** @fumoca/storage: storage provider interface and built-in providers. See SPECS.md §8. */
export {
  addSeriesColumn,
  addSheet,
  columnNameError,
  createSeriesSheet,
  createSheet,
  createWorkbook,
  DEFAULT_SERIES_PERIODS,
  FILE_EXTENSION,
  FILE_FORMAT,
  FILE_VERSION,
  nextSheetName,
  PERIOD_COLUMN,
  parseWorkbook,
  renameSeriesColumn,
  SERIES_TYPES,
  type SeriesSettings,
  type SeriesType,
  type Sheet,
  serializeWorkbook,
  setCell,
  setSeriesSettings,
  type Workbook,
  WorkbookFormatError,
} from "./workbook";
